name: fusionflow

target:
  _target_: scripts.network.models.raliflow.RaLiFlow
  decoder_option: gru # choices: [linear, gru]
  num_iters: 4
  voxel_size: ${voxel_size}
  point_cloud_range: ${point_cloud_range}
  # dynamic_mask: ${dynamic_mask}

val_monitor: Lidar val/Three-way